services:
  - type: web
    name: studybud
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn studybud.wsgi"
    envVars:
      - key: SECRET_KEY
        value: 'django-insecure-c8+^%0v@t^&%1w)$5p&o@4w71ec(p866d)$10r9zeqgdzx3@gt'
      - key: DATABASE_URL
        value: 'postgresql://studybud_db_w36j_user:btCLHtctHBikbi8SCGkmZOiUBQpKKfRx@dpg-d0krfm8gjchc73ej3df0-a.oregon-postgres.render.com/studybud_db_w36j'
